### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by bassu** [dgraham/xcode-low-key-syntax#1]
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `xcode-low-key-syntax` package

**Comment by bassu** [comment]
Thanks for the quick fix!

**Comment by dgraham** [comment]
Thanks for reporting this. I didn't see the deprecations because I typically use Atom with the status bar hidden.

**Comment by bassu** [comment]
@dgraham LOL :shirt:
